version: '3'
services:
    web:
        build:
            dockerfile: Dockerfile
            context: .
        links:
           - mongo
        command: [bash]
        tty: true
        stdin_open: true
        environment:
            DB: mongodb://root:example@mongo/
        ports:
            - 8080:80
        volumes:
            - ./:/srv
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
      